### PR TITLE
docs(website): initialize i18n

### PR DESCRIPTION
**Pull request by jsun969**
## Summary/ Motivation (TLDR;)

Initialize i18n for docusaurus docs. Add a little bit Chinese translation (for homepage and Introduction docs).

## Problem

~~The SVG (or all static files) cannot be loaded in i18n dev mode~~
Oh it works fine on production. That's good xD

https://github.com/jsun969/jest-preview/blob/c64240c4801844663d84fc637a4d71bf0067d631/website/src/components/HomepageFeatures/index.tsx#L12

### For homepage

Modify `/website/i18n/vi-VN/code.json` Line2-Line64 (where id start with `home.`)

### For footer and navbar

Modify files in `/website/i18n/vi-VN/docusaurus-theme-classic`

### For docs

Modify `/website/i18n/vi-VN/docusaurus-plugin-content-docs/current.json` for directory  
Then see [i18n - Tutorial | Docusaurus #translate-markdown-files](https://docusaurus.io/docs/i18n/tutorial#translate-markdown-files)

## Notice

The `tagline` in docusaurus config is no longer used for homepage subtitle.

### CODE REVIEW

**Comment by jsun969** [comment]
To fix the problem: The SVG (or all static files) cannot be loaded in i18n dev mode  
We must refactor the static files to `src={require("...")}` or `src={useBaseUrl("/foo")}`

Docs: https://docusaurus.io/docs/static-assets#referencing-your-static-asset

I think it's a big refactor and unnessary. What do you think about it?

**Comment by nvh95** [comment]
That's an awesome PR. I will take a look very soon. Thank you very much for your support @jsun969 <3

**Comment by jsun969** [comment]
Best new year gift ever <3

**Comment by nvh95** [comment]
Thank you @jsun969 for your support. Happy new year <3

**Pull request merged**
