### PR TITLE
Add translation guide

### PR DESCRIPTION
**Pull request by jsun969**
## Summary/ Motivation (TLDR;)

Add translation guide

### CODE REVIEW

**Comment by nvh95** [comment]
Can you take a look @jsun969? (Well not sure why the public logs cannot be accessed publicly for now)
Please let me know if you need my help on this.

**Comment by jsun969** [comment]
I jump to TRANSLATION.md with relative path. Maybe this made the docs `website/scripts/contributing.js` script error

**Comment by jsun969** [comment]
lol it works fine now

**Review by nvh95 — APPROVED** [review]
LGTM!

**Pull request merged**
